services:
  postgres:
    image: postgres:15
    container_name: todolist_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist_network

  app:
    build: .
    container_name: todolist_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - todolist_network

volumes:
  postgres_data:

networks:
  todolist_network:
